name: indus_reader
description: A complete PDF Reader and Editor app with Pro features.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # In sabhi libraries ko 'any' kar diya hai taaki koi version error na aaye
  syncfusion_flutter_pdfviewer: any
  syncfusion_flutter_pdf: any
  file_picker: any
  shared_preferences: any
  path_provider: any
  google_mlkit_text_recognition: any

flutter:
  uses-material-design: true
