name: indus_reader
description: A complete PDF Reader and Editor app with Pro features.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # In sabhi libraries ko 'any' kar diya hai taaki koi version error na aaye
  syncfusion_flutter_pdfviewer: any
  syncfusion_flutter_pdf: any
  file_picker: any
  shared_preferences: any
  path_provider: any
  google_mlkit_text_recognition: any
  # Document Scanner ke liye library
  google_mlkit_document_scanner: any
  receive_sharing_intent: ^1.6.2
  
  # --- NAYE CLOUD AI DEPENDENCIES YAHAN HAIN ---
  google_generative_ai: ^0.4.6
  flutter_dotenv: ^5.1.0

# App icon generate karne ke liye library
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  # NAYA: .env file ko app mein include karne ke liye
  assets:
    - .env

# iOS ko false kar diya taaki error na aaye
flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "icon.png"
  min_sdk_android: 21
