import 'dart:io';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:path_provider/path_provider.dart';
import 'package:syncfusion_flutter_pdf/pdf.dart';
import 'flashcard_screen.dart'; // <--- NAYI FILE IMPORT KI HAI

class MyNotesScreen extends StatefulWidget {
  const MyNotesScreen({super.key});

  @override
  State<MyNotesScreen> createState() => _MyNotesScreenState();
}

class _MyNotesScreenState extends State<MyNotesScreen> {
  Map<String, List<String>> _allNotes = {};
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _loadNotes();
  }

  Future<void> _loadNotes() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    Set<String> keys = prefs.getKeys();
    
    Map<String, List<String>> tempNotes = {};
    for (String key in keys) {
      if (key.startsWith('notes_')) {
        String pdfName = key.replaceFirst('notes_', '');
        List<String> notes = prefs.getStringList(key) ?? [];
        if (notes.isNotEmpty) {
          tempNotes[pdfName] = notes;
        }
      }
    }
    
    setState(() {
      _allNotes = tempNotes;
      _isLoading = false;
    });
  }

  Future<void> _exportToPdf(String subjectName, List<String> notes) async {
    try {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('⏳ Generating PDF... Please wait.'), backgroundColor: Colors.blueAccent),
      );

      PdfDocument document = PdfDocument();
      
      String cleanName = subjectName.replaceAll('.pdf', '');
      String fullText = "Smart Notes: $cleanName\n";
      fullText += "Generated by Indus AI\n";
      fullText += "=========================================\n\n";
      
      for (String note in notes) {
        fullText += "$note\n\n";
      }

      PdfStandardFont font = PdfStandardFont(PdfFontFamily.helvetica, 12);
      PdfTextElement textElement = PdfTextElement(text: fullText, font: font);
      
      PdfPage page = document.pages.add();
      textElement.draw(
        page: page,
        bounds: Rect.fromLTWH(0, 0, page.getClientSize().width, page.getClientSize().height),
        format: PdfLayoutFormat(layoutType: PdfLayoutType.paginate),
      );

      List<int> bytes = document.saveSync();
      document.dispose();

      final dir = await getApplicationDocumentsDirectory();
      String outputPath = '${dir.path}/SmartNotes_$cleanName.pdf';
      File file = File(outputPath);
      await file.writeAsBytes(bytes);

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('✅ PDF Saved Successfully: SmartNotes_$cleanName.pdf'),
          backgroundColor: Colors.green,
          duration: const Duration(seconds: 4),
        ),
      );
      
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('❌ Error generating PDF: $e'), backgroundColor: Colors.red),
      );
    }
  }

  Future<void> _deleteNotes(String key) async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    await prefs.remove(key);
    _loadNotes(); 
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('🗑️ Notes deleted successfully!')),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('📝 My Smart Notes', style: TextStyle(fontWeight: FontWeight.bold)),
        backgroundColor: Colors.deepPurpleAccent,
        foregroundColor: Colors.white,
      ),
      backgroundColor: Colors.grey.shade100,
      body: _isLoading 
        ? const Center(child: CircularProgressIndicator())
        : _allNotes.isEmpty
          ? const Center(
              child: Text(
                "Koi notes save nahi kiye hain abhi tak.\nPadhte time 'Save Note' par click karein!",
                textAlign: TextAlign.center,
                style: TextStyle(fontSize: 16, color: Colors.grey),
              ),
            )
          : ListView.builder(
              padding: const EdgeInsets.all(12),
              itemCount: _allNotes.length,
              itemBuilder: (context, index) {
                String pdfName = _allNotes.keys.elementAt(index);
                List<String> notes = _allNotes[pdfName]!;
                
                return Card(
                  elevation: 3,
                  margin: const EdgeInsets.only(bottom: 12),
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                  child: ExpansionTile(
                    leading: const CircleAvatar(
                      backgroundColor: Colors.deepPurpleAccent,
                      child: Icon(Icons.library_books, color: Colors.white),
                    ),
                    title: Text(
                      pdfName, 
                      style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
                    ),
                    subtitle: Text("${notes.length} points saved", style: const TextStyle(color: Colors.green)),
                    children: [
                      Container(
                        padding: const EdgeInsets.all(16),
                        color: Colors.deepPurple.shade50,
                        width: double.infinity,
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              notes.join("\n\n"),
                              style: const TextStyle(fontSize: 14, color: Colors.black87),
                            ),
                            const SizedBox(height: 16),
                            // --- YAHAN FLASHCARD BUTTON ADD KIYA HAI ---
                            Wrap(
                              spacing: 8,
                              runSpacing: 8,
                              alignment: WrapAlignment.end,
                              children: [
                                OutlinedButton.icon(
                                  onPressed: () => _deleteNotes('notes_$pdfName'),
                                  icon: const Icon(Icons.delete, color: Colors.red, size: 18),
                                  label: const Text("Delete", style: TextStyle(color: Colors.red)),
                                ),
                                ElevatedButton.icon(
                                  onPressed: () => _exportToPdf(pdfName, notes),
                                  icon: const Icon(Icons.picture_as_pdf, size: 18),
                                  label: const Text("Export to PDF"),
                                  style: ElevatedButton.styleFrom(
                                    backgroundColor: Colors.deepPurpleAccent,
                                    foregroundColor: Colors.white,
                                  ),
                                ),
                                ElevatedButton.icon(
                                  onPressed: () {
                                    Navigator.push(
                                      context, 
                                      MaterialPageRoute(
                                        builder: (context) => FlashcardScreen(subjectName: pdfName, notes: notes)
                                      )
                                    );
                                  },
                                  icon: const Icon(Icons.style, size: 18),
                                  label: const Text("Flashcards"),
                                  style: ElevatedButton.styleFrom(
                                    backgroundColor: Colors.orangeAccent,
                                    foregroundColor: Colors.white,
                                  ),
                                ),
                              ],
                            )
                          ],
                        ),
                      )
                    ],
                  ),
                );
              },
            ),
    );
  }
}
