import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart'; // <--- NAYA IMPORT FONT LOAD KARNE KE LIYE
import 'package:shared_preferences/shared_preferences.dart';
import 'package:path_provider/path_provider.dart';
import 'package:syncfusion_flutter_pdf/pdf.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import 'flashcard_screen.dart';

class MyNotesScreen extends StatefulWidget {
  const MyNotesScreen({super.key});

  @override
  State<MyNotesScreen> createState() => _MyNotesScreenState();
}

class _MyNotesScreenState extends State<MyNotesScreen> {
  Map<String, List<String>> _allNotes = {};
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _loadNotes();
  }

  Future<void> _loadNotes() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    Set<String> keys = prefs.getKeys();
    
    Map<String, List<String>> tempNotes = {};
    for (String key in keys) {
      if (key.startsWith('notes_')) {
        String pdfName = key.replaceFirst('notes_', '');
        List<String> notes = prefs.getStringList(key) ?? [];
        if (notes.isNotEmpty) {
          tempNotes[pdfName] = notes;
        }
      }
    }
    
    setState(() {
      _allNotes = tempNotes;
      _isLoading = false;
    });
  }

  Future<void> _exportToPdf(String subjectName, List<String> notes) async {
    try {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('⏳ Generating PDF... Please wait.'), backgroundColor: Colors.deepPurpleAccent),
      );

      PdfDocument document = PdfDocument();
      
      String cleanName = subjectName.replaceAll('.pdf', '');
      String fullText = "Smart Notes: $cleanName\n";
      fullText += "Generated by Indus AI\n";
      fullText += "=========================================\n\n";
      
      for (String note in notes) {
        String cleanNote = note.replaceAll('**', '').replaceAll('* ', '• ');
        fullText += "$cleanNote\n\n";
      }

      // --- HINDI FONT LOAD KARNE KA NAYA LOGIC ---
      PdfFont font;
      try {
        // Hum assets folder se hindi font utha rahe hain
        final ByteData fontData = await rootBundle.load('assets/fonts/hindi_font.ttf');
        font = PdfTrueTypeFont(fontData.buffer.asUint8List(), 12);
      } catch (e) {
        debugPrint("Font Error: $e");
        // Agar font nahi mila toh fallback (is case mein error aa sakta hai agar text Hindi hua)
        font = PdfStandardFont(PdfFontFamily.helvetica, 12);
      }
      
      PdfTextElement textElement = PdfTextElement(text: fullText, font: font);
      
      PdfPage page = document.pages.add();
      textElement.draw(
        page: page,
        bounds: Rect.fromLTWH(0, 0, page.getClientSize().width, page.getClientSize().height),
        format: PdfLayoutFormat(layoutType: PdfLayoutType.paginate),
      );

      List<int> bytes = document.saveSync();
      document.dispose();

      final dir = await getApplicationDocumentsDirectory();
      String outputPath = '${dir.path}/SmartNotes_$cleanName.pdf';
      File file = File(outputPath);
      await file.writeAsBytes(bytes);

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('✅ PDF Saved: SmartNotes_$cleanName.pdf'),
          backgroundColor: Colors.green,
          behavior: SnackBarBehavior.floating,
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
          duration: const Duration(seconds: 4),
        ),
      );
      
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('❌ Error generating PDF: $e'), backgroundColor: Colors.red),
      );
    }
  }

  Future<void> _deleteNotes(String key) async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    await prefs.remove(key);
    _loadNotes(); 
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: const Text('🗑️ Notes deleted successfully!'),
        behavior: SnackBarBehavior.floating,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF4F6F9), 
      appBar: AppBar(
        title: const Text('My Smart Notes', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 22, letterSpacing: 0.5)),
        backgroundColor: Colors.deepPurpleAccent,
        foregroundColor: Colors.white,
        elevation: 0,
        centerTitle: true,
        shape: const RoundedRectangleBorder(
          borderRadius: BorderRadius.vertical(bottom: Radius.circular(20)),
        ),
      ),
      body: _isLoading 
        ? const Center(child: CircularProgressIndicator(color: Colors.deepPurpleAccent))
        : _allNotes.isEmpty
          ? Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Icon(Icons.library_books, size: 80, color: Colors.grey.shade400),
                  const SizedBox(height: 16),
                  const Text(
                    "No notes saved yet!",
                    style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, color: Colors.black54),
                  ),
                  const SizedBox(height: 8),
                  Text(
                    "Read a PDF and click 'Save Note'\nto see the magic here.",
                    textAlign: TextAlign.center,
                    style: TextStyle(fontSize: 15, color: Colors.grey.shade600, height: 1.5),
                  ),
                ],
              ),
            )
          : ListView.builder(
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 20),
              itemCount: _allNotes.length,
              itemBuilder: (context, index) {
                String pdfName = _allNotes.keys.elementAt(index);
                List<String> notes = _allNotes[pdfName]!;
                
                return Container(
                  margin: const EdgeInsets.only(bottom: 16),
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(20),
                    boxShadow: [
                      BoxShadow(
                        color: Colors.deepPurpleAccent.withOpacity(0.08),
                        blurRadius: 15,
                        offset: const Offset(0, 5),
                      ),
                    ],
                  ),
                  child: Theme(
                    data: Theme.of(context).copyWith(dividerColor: Colors.transparent),
                    child: ExpansionTile(
                      tilePadding: const EdgeInsets.symmetric(horizontal: 20, vertical: 8),
                      leading: Container(
                        padding: const EdgeInsets.all(12),
                        decoration: BoxDecoration(
                          gradient: const LinearGradient(
                            colors: [Colors.deepPurpleAccent, Colors.purpleAccent],
                            begin: Alignment.topLeft,
                            end: Alignment.bottomRight,
                          ),
                          borderRadius: BorderRadius.circular(14),
                        ),
                        child: const Icon(Icons.description, color: Colors.white, size: 24),
                      ),
                      title: Text(
                        pdfName.replaceAll('.pdf', ''), 
                        style: const TextStyle(fontWeight: FontWeight.w700, fontSize: 17, color: Colors.black87),
                      ),
                      subtitle: Padding(
                        padding: const EdgeInsets.only(top: 4),
                        child: Text(
                          "${notes.length} Important Points", 
                          style: const TextStyle(color: Colors.green, fontWeight: FontWeight.w600, fontSize: 13),
                        ),
                      ),
                      iconColor: Colors.deepPurpleAccent,
                      children: [
                        Container(
                          width: double.infinity,
                          padding: const EdgeInsets.all(20),
                          decoration: BoxDecoration(
                            color: Colors.deepPurple.shade50.withOpacity(0.5),
                            borderRadius: const BorderRadius.only(
                              bottomLeft: Radius.circular(20), 
                              bottomRight: Radius.circular(20)
                            ),
                          ),
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              MarkdownBody(
                                data: notes.join("\n\n---\n\n"), 
                                selectable: true,
                                styleSheet: MarkdownStyleSheet(
                                  p: const TextStyle(fontSize: 15, height: 1.6, color: Colors.black87),
                                  strong: const TextStyle(fontWeight: FontWeight.w800, color: Colors.deepPurple), 
                                  listBullet: const TextStyle(color: Colors.deepPurpleAccent, fontSize: 18),
                                  horizontalRuleDecoration: BoxDecoration(
                                    border: Border(top: BorderSide(width: 1, color: Colors.grey.shade300)),
                                  ),
                                ),
                              ),
                              
                              const SizedBox(height: 24),
                              
                              Row(
                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                children: [
                                  IconButton(
                                    onPressed: () => _deleteNotes('notes_$pdfName'),
                                    icon: const Icon(Icons.delete_outline),
                                    color: Colors.redAccent,
                                    tooltip: "Delete Notes",
                                  ),
                                  
                                  Row(
                                    children: [
                                      ElevatedButton.icon(
                                        onPressed: () {
                                          Navigator.push(
                                            context, 
                                            MaterialPageRoute(
                                              builder: (context) => FlashcardScreen(subjectName: pdfName, notes: notes)
                                            )
                                          );
                                        },
                                        icon: const Icon(Icons.style, size: 18),
                                        label: const Text("Flashcards", style: TextStyle(fontWeight: FontWeight.bold)),
                                        style: ElevatedButton.styleFrom(
                                          backgroundColor: Colors.orangeAccent,
                                          foregroundColor: Colors.white,
                                          elevation: 2,
                                          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                                          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                                        ),
                                      ),
                                      const SizedBox(width: 10),
                                      ElevatedButton.icon(
                                        onPressed: () => _exportToPdf(pdfName, notes),
                                        icon: const Icon(Icons.picture_as_pdf, size: 18),
                                        label: const Text("Export", style: TextStyle(fontWeight: FontWeight.bold)),
                                        style: ElevatedButton.styleFrom(
                                          backgroundColor: Colors.deepPurpleAccent,
                                          foregroundColor: Colors.white,
                                          elevation: 2,
                                          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                                          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                                        ),
                                      ),
                                    ],
                                  ),
                                ],
                              )
                            ],
                          ),
                        )
                      ],
                    ),
                  ),
                );
              },
            ),
    );
  }
}
