name: Build Indus Reader APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Generate Missing Android Files
        run: |
          flutter create temp_app --platforms=android --org com.indusreader
          cp -r temp_app/android ./android
          rm -rf temp_app

      - name: Install Dependencies
        run: flutter pub get

      # YAHAN CHANGE KIYA HAI: --release ki jagah --debug kar diya hai
      - name: Build APK
        run: flutter build apk --debug

      # YAHAN BHI CHANGE KIYA HAI: app-release.apk ki jagah app-debug.apk kar diya hai
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: IndusReader-APK
          path: build/app/outputs/flutter-apk/app-debug.apk
